improve workflow summary

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,13 +1,14 @@
 name: Cargo Build & Test
 
-on: [push, pull_request]
+on:
+  [push, pull_request]
 
 env:
   CARGO_TERM_COLOR: always
 
 jobs:
   build_and_test:
-    name: Rust project - latest
+    name: Rust Project - Latest
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -16,19 +17,42 @@ jobs:
           - nightly
     steps:
       - uses: actions/checkout@v4
-      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
-      - name: Install Clippy and lint
+
+      - name: Set up Rust toolchain
+        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
+
+      - name: Install Clippy and Lint
         run: rustup component add clippy && cargo clippy
-      - run: cargo build --verbose
+
+      - name: Build project
+        run: cargo build --verbose
+
       - name: Run tests and save output
         run: |
           cargo test --all --verbose 2>&1 | tee test_output.txt
         continue-on-error: true
-      - name: Generate summary
+
+      - name: Analyze Test Results
         run: |
-          total_tests=$(grep -m 1 -o 'running [0-9]\+ test' test_output.txt | grep -o '[0-9]\+')
-          echo "Total tests: $total_tests" >> $GITHUB_STEP_SUMMARY
-          test_states=($(grep  -m 1 -o 'test result: ok. [0-9]\+ passed; [0-9]\+ failed;' test_output.txt | grep -o '[0-9]\+'))
-          echo "Failed tests: ${test_states[1]}" >> $GITHUB_STEP_SUMMARY
-          echo "Passed tests: ${test_states[0]}" >> $GITHUB_STEP_SUMMARY
-        continue-on-error: true
+          # Extract test results
+          total_tests=$(grep -Eo 'running [0-9]+ tests?' test_output.txt | grep -Eo '[0-9]+' | awk '{s+=$1} END {print s}')
+          passed_tests=$(grep -c '^test .* \.\.\. ok$' test_output.txt)
+          failed_tests=$(grep -c '^test .* \.\.\. FAILED$' test_output.txt)
+          # Summarize failed tests
+          echo "## Test Summary" >> $GITHUB_STEP_SUMMARY
+          echo "| Total Tests | Passed | Failed |" >> $GITHUB_STEP_SUMMARY
+          echo "|-------------|--------|--------|" >> $GITHUB_STEP_SUMMARY
+          echo "| $total_tests | $passed_tests | $failed_tests |" >> $GITHUB_STEP_SUMMARY
+
+          if [ "$failed_tests" -gt 0 ]; then
+            echo "## Failed Tests" >> $GITHUB_STEP_SUMMARY
+            echo "| Test Name | Failure Message |" >> $GITHUB_STEP_SUMMARY
+            echo "|-----------|-----------------|" >> $GITHUB_STEP_SUMMARY
+            grep '^test .* ... FAILED' test_output.txt | while read -r line; do
+              test_name=$(echo "$line" | awk '{print $2}')
+              failure_msg=$(grep -A2 "$test_name" test_output.txt | tail -n 1)
+              echo "| $test_name | $failure_msg |" >> $GITHUB_STEP_SUMMARY
+            done
+            exit 1
+          fi
+
